# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-aws
env:
  EB_PACKAGE_S3_BUCKET_NAME: 'my flask app package'
  EB_APPLICATION_NAMW      : 'flask'
  EB_ENVIRONMENT           : 'flask-env'
  DEPLOY_PACKAGE_NAME      : "flask app_${{github.sha}}.zip"
  AWS_REGION_NAME          : 'eu-central-1'  

on:
  push:
    branches: 
      - master
# Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci-part:
    runs-on: ubuntu-latest

    steps:
      - name: git clone our repo
        uses: actions/checkout@v1

      - name: Create zip dep package
        run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
        
